ProjectChat/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('chat.urls')),
]

chat/urls.py
from django.urls import path

from . import views
from django.conf import settings
from django.conf.urls.static import static


app_name = 'chat'
urlpatterns = [
    
    path("", views.register_view, name="register_view"),
    path("chat/", views.index_view, name="index_view"),
    path("chat/<room_name>", views.room_view, name="room_view"),
    path('signoff/',views.SignOff,name='signoff'),
]

chat/models.py
from django.db import models
from django.contrib.auth.models import User

from django.utils.text import slugify
from django.urls import reverse

class Room(models.Model):
    name = models.CharField(max_length=128)
    slug = models.SlugField(blank=True) 
    online = models.ManyToManyField(to=User, blank=True)

    def add_user_to_online(self, user):
        if user not in self.online.all():
            self.online.add(user)
            self.save()

    def remove_user_from_online(self, user):
        if user in self.online.all():
            self.online.remove(user)
            self.save()

    def get_online_users(self):
        return self.online.all()


    
    def get_absolute_url(self):
        return reverse("chat:room_view",kwargs={"room_name":self.slug})
    @property
    def data(self):
        return self.message_set.all()

    def save(self, *args,**kwargs) -> str:
        if not self.slug:
            self.slug = slugify(self.name)
        super().save(*args,**kwargs)

    def __str__(self):
        return f'{self.name} ({self.online.count()} online)'  

class Message(models.Model):
    user = models.ForeignKey(to=User, on_delete=models.CASCADE)
    room = models.ForeignKey(to=Room, on_delete=models.CASCADE)
    content = models.CharField(max_length=255)
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.user.username}: {self.content} [{self.timestamp}]'

chat/forms.py
from django.contrib.auth.forms import UserCreationForm,AuthenticationForm
from django.contrib.auth.models import User
from django import forms


class LoginForm(AuthenticationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'Usuario','class': 'lg-username',}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={'placeholder': 'Contraseña','class': 'lg-passwd',}))

    class Meta:
        model = User
        fields = ['username','password']

class RegisterForm(UserCreationForm):

    username = forms.CharField(max_length=100,
                               required=True,
                               widget=forms.TextInput(attrs={'placeholder': 'Enter your username',
                                                             'class': 'rg-username',
                                                             'autocomplete':'off',
                                                             }))
    
    password1 = forms.CharField(max_length=50,
                                required=True,
                                widget=forms.PasswordInput(attrs={'placeholder': 'Enter your password',
                                                                  'class': 'rg-passwd',
                                                                  'data-toggle': 'password',
                                                                  }))
    password2 = forms.CharField(max_length=50,
                                required=True,
                                widget=forms.PasswordInput(attrs={'placeholder': 'Confirm your password',
                                                                  'class': 'rg-passwd-conf',
                                                                  'data-toggle': 'password',
                                                                  }))

    class Meta:
        model = User
        fields = ['username','password1', 'password2']

chat/views.py
from django.contrib.auth import login,logout,authenticate

from chat.models import Room
from django.shortcuts import render,redirect, get_object_or_404
from django.contrib.auth.decorators import login_required

from .forms import RegisterForm,LoginForm

def register_view(request):

    login_form = LoginForm()
    registro_form = RegisterForm()

    if request.method == 'POST':
        if 'login' in request.POST:
            login_form = LoginForm(request, request.POST)
            if login_form.is_valid():
                
                username = login_form.cleaned_data['username']
                password = login_form.cleaned_data['password']
                user = authenticate(request, username=username, password=password)

                if user is not None:
                    login(request, user)
                    return redirect('chat:index_view')
        
        elif 'register' in request.POST:
            registro_form = RegisterForm(request.POST)
            if registro_form.is_valid():
                user = registro_form.save()

                login(request, user)
                return redirect('chat:index_view')

    return render(request, 'chat/register.html', {'login_form': login_form, 'registro_form': registro_form})


def SignOff(request):
    logout(request)
    return redirect('chat:register_view')


@login_required
def index_view(request):
    rooms = Room.objects.all()
    if request.method == 'POST':
        room_name = request.POST.get('room-name')
        if room_name:
            chat_room, created = Room.objects.get_or_create(name=room_name)
            return redirect("chat:room_view",chat_room.slug)
    return render(request, 'chat/index_view.html', {'rooms': rooms})

@login_required
def room_view(request, room_name):
    obj = get_object_or_404(Room,slug=room_name)
    return render(request,'chat/room_view.html',{
        'name':obj.name,
        'slug':obj.slug,
        'data':obj.data,
    })

chat/templates/chat/index_view.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <title>Lista de Sala</title>
        <link rel="icon" type="image/x-icon" href="{% static 'chat.ico' %}">
        <title>Lista de Usuarios Personalizados</title>
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/fontawesome.min.css">
    
        <link rel="stylesheet" href="{% static 'css/app-chat.css' %}">
        <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
        <link rel="stylesheet" href="{% static 'css/scrollbar.css' %}">
        <link rel="stylesheet" href="{% static 'css/theme.css' %}">
    
        <link href='https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css' rel='stylesheet'>
        <style>
            #roomSelect {
                height: 300px;
            }
        </style>
    </head>
    <body>
        <div class="container mt-3 p-5">
            <h2>Django Channels Group</h2>
            <div class="position-relative top-0 end-0 text-end pb-3">
                <a href="{% url 'chat:signoff' %}" class="btn btn-danger button-49 text-end" style="display: inline-block; text-align: center;text-decoration: none;">Cerrar Session</a>
            </div>
            <div class="row">
                <div class="col-12 col-md-8">
                    <div class="mb-2">
                        <form method="POST">
                            {% csrf_token %}
                            <div class="forms-group">
                                <label for="roomInput">Si la sala aún no existe, se creará para usted:</label>
                                <input type="text" class="form-control" name="room-name">
                                <small id="roomInputHelp" class="form-text text-muted">Ingrese el nombre de una Sala para conectarse a ella:</small>
                                <br>
                                <button type="submit" class="btn btn-primary mt-3">Conectar</button>
                            </div>
                        </form>
                    </div>

                    
                        
                </div>                
                <div class="col-md-6 col-lg-4 order-2 mb-4">
                    <div class="card h-100">
                    <div class="card-header d-flex align-items-center justify-content-between">
                        <h5 class="card-title m-0 me-2">Salas Activas</h5>                        
                    </div>
                    <div class="card-body">
                        <ul class="p-0 m-0">
                            {% if rooms %}
                            {% for room in rooms %}
                                <li class="d-flex mb-2 pb-1">
                                    <a href="{{room.get_absolute_url}}" style="width: 100%">
                                        <div class="d-flex w-100 flex-wrap align-items-center justify-content-between">
                                            <div class="me-2">
                                                <span class="mb-0">{{room.name}}</span>                                        
                                            </div>
                                        </div>
                                    </a>
                                </li>
                            {% endfor %}
                            {% endif %}
                            <!-- <li class="d-flex mb-4 pb-1">
                                <a href="#" style="width: 100%">
                                    <div class="d-flex w-100 flex-wrap align-items-center justify-content-between gap-2">
                                        <div class="me-2">
                                            <span class="mb-0">Send money</span>                                        
                                        </div>
                                    </div>
                                </a>
                            </li>
                            <li class="d-flex mb-4 pb-1">
                                <a href="#" style="width: 100%">
                                    <div class="d-flex w-100 flex-wrap align-items-center justify-content-between gap-2">
                                        <div class="me-2">
                                            <span class="mb-0">Send money</span>                                        
                                        </div>
                                    </div>
                                </a>
                            </li>
                            <li class="d-flex mb-4 pb-1">
                                <a href="#" style="width: 100%">
                                    <div class="d-flex w-100 flex-wrap align-items-center justify-content-between gap-2">
                                        <div class="me-2">
                                            <span class="mb-0">Send money</span>                                        
                                        </div>
                                    </div>
                                </a>
                            </li> -->
                        </ul>
                    </div>
                    </div>
                </div>
            </div>
        </div>
    </body>
</html>

chat/templates/chat/register.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <title>Chat Django Channel - Henry Ccoillo</title>
    <link rel="icon" type="image/x-icon" href="{% static 'chat.ico' %}">
    <link rel="stylesheet" href="{% static 'css/login.css' %}">
    <link rel="stylesheet" href="{% static 'css/iziToast.min.css' %}">
    <script src="https://kit.fontawesome.com/64d58efce2.js" crossorigin="anonymous"></script>
</head>
<body>
    <div class="container">
        <div class="forms-container">
            <div class="signin-signup">
                <form method="post" class="sign-in-form" onsubmit="return validateFormLogin()">
                    {% csrf_token %}
                    <h2 class="title">Iniciar Sesíon</h2>
                    <div class="input-field">
                        <i class="fas fa-user"></i>
                        <!-- <input type="text" placeholder="Username" /> -->
                        {{ login_form.username }}
                    </div>
                    <div class="input-field">
                        <i class="fas fa-lock"></i>
                        <!-- <input type="password" placeholder="Password" /> -->
                        {{ login_form.password }}
                    </div>
                    <!-- <input type="submit" name="login" value="Iniciar Sesíon" class="sign-btn" /> -->
                    <input type="submit" name="login" value="Login" class="btn solid" />                    
                </form>


                <form method="post" class="sign-up-form" onsubmit="return validateFormRegister()">
                    {% csrf_token %}
                    <h2 class="title">Registrarse</h2>
                    <div class="input-field">
                        <i class="fas fa-user"></i>
                        <!-- <input type="text" placeholder="Username" /> -->
                        {{registro_form.username}}
                    </div>
                    <div class="input-field">
                        <i class="fas fa-lock"></i>
                        {{registro_form.password1}}
                        <!-- <input type="email" placeholder="Email" /> -->
                    </div>
                    <div class="input-field">
                        <i class="fas fa-lock"></i>
                        {{registro_form.password2}}
                        <!-- <input type="password" placeholder="Password" /> -->
                    </div>
                    <input type="submit" name="register" class="btn" value="Sign up" />
                    <!-- <input type="submit" name="register" value="Registrarte" class="sign-btn" /> -->
                </form>
            </div>
        </div>

        <div class="panels-container">
            <div class="panel left-panel">
                <div class="content">
                    <h3>Nuevo aquí ?</h3>
                    <p>
                      Experimenta la magia de la comunicación en tiempo real con Django Channels y participa en conversaciones significativas con personas.
                    </p>
                    <button class="btn transparent" id="sign-up-btn">
                        Regístrate
                    </button>
                </div>
                <img src="{% static 'img/log.svg' %}" class="image" alt="" />
            </div>
            <div class="panel right-panel">
                <div class="content">
                    <h3>¡Bienvenido de vuelta!</h3>
                    <p>
                      Ingresa tus credenciales para continuar disfrutando de nuestra plataforma de comunicación en tiempo real con Django Channels.
                    </p>
                    <button class="btn transparent" id="sign-in-btn">
                      Iniciar Sesión
                    </button>
                </div>
                <img src="{% static 'img/register.svg' %}" class="image" alt="" />
            </div>
        </div>
    </div>

    <script src="{% static 'js/iziToast.min.js' %}"></script>
    <script src="{% static 'js/sweetalert.min.js' %}"></script>

 
        <script>
                    
const sign_in_btn = document.querySelector("#sign-in-btn");
const sign_up_btn = document.querySelector("#sign-up-btn");
const container = document.querySelector(".container");

sign_up_btn.addEventListener("click", () => {
    container.classList.add("sign-up-mode");
    });

sign_in_btn.addEventListener("click", () => {
    container.classList.remove("sign-up-mode");
    });

function validateFormLogin() {
    const lgUsername = document.querySelector(".lg-username").value;  
    const lgPassword = document.querySelector(".lg-passwd").value;
    const lgUsernameRegex = /^[a-zA-Z0-9_]+$/;

    if (!lgUsernameRegex.test(lgUsername)) {
        iziToast.error({
            title: 'Error, Nombre de Usuario',
            message: 'El nombre de usuario solo debe contener letras, números y guiones bajos (_).',
            position: 'topCenter'
        });
        return false;
    }
    
    if (lgPassword.length < 1) {
        iziToast.error({
            title: 'Error, Contraseña',
            message: 'Ingrese su contraseña.',
            position: 'topCenter'
        });
        return false;
    }
    
    return true;
    }

function validateFormRegister() {
    console.log("asdasaaaaaaaa");
    const rgUsername = document.querySelector(".rg-username").value;
    const rgPassword = document.querySelector(".rg-passwd").value;
    const rgPasswordConf = document.querySelector(".rg-passwd-conf").value;
    const rgUsernameRegex = /^[a-zA-Z0-9_]+$/;
    const rgPasswordRegex = /^(?=.*[A-Z])(?=.*\d)(?=.*[@$!%*?&])[A-Za-z\d@$!%*?&]{8,}$/;

    
    if (!rgUsernameRegex.test(rgUsername)) {
        iziToast.error({
            title: 'Error, Nombre de Usuario',
            message: 'El nombre de usuario solo debe contener letras, números y guiones bajos (_).',
            position: 'topCenter'
        });
        return false;
    }

    if (!rgPasswordRegex.test(rgPassword)) {
        iziToast.error({
            title: 'Error, Contraseña',
            message: 'La contraseña debe tener al menos 8 caracteres, una mayúscula y un carácter especial.',
            position: 'topCenter'
        });
        return false;
    }

    if (rgPassword !== rgPasswordConf) {
        iziToast.error({
            title: 'Error, Contraseña',
            message: 'Las contraseñas no coinciden.',
            position: 'topCenter'
        });
        return false;
    }
                
    return true;
}

        </script>

    {% if login_form.errors %}
    <script>
        swal('Error!','{% for field, error_list in login_form.errors.items %}{% for error in error_list %}{{ error }}{% endfor %}{% endfor %}', 'error');        
    </script>
    {% endif %}

    {% if registro_form.errors %}
    <script>
        const errorsList = [{% for field, error_list in registro_form.errors.items %}"{% for error in error_list %}{{ error }}{% endfor %}",{% endfor %}];
        const errorsText = errorsList.join('\n');
        swal('Error!', errorsText, 'error');
    </script>
    {% endif %}
</body>

</html>